Coverage Test

diff --git a/.github/workflows/website.yml b/.github/workflows/website.yml
--- a/.github/workflows/website.yml
+++ b/.github/workflows/website.yml
@@ -38,12 +38,13 @@ jobs:
 
       - name: Check coverage threshold
         run: |
-          COVERAGE=$(grep -Po 'All files.*? \K\d+(?=%)' coverage/lcov-report/index.html)
-          echo "Coverage is $COVERAGE%"
-          if [ "$COVERAGE" -ge 50 ]; then
-            echo "::set-output name=coverage_passed::true"
+          COVERAGE=$(jq '.total.statements.pct' coverage/lcov-report/index.html)
+          if (( $(echo "$COVERAGE < 50.0" |bc -l) )); then
+            echo "Test coverage ($COVERAGE%) is below the required threshold of 50%."
+            exit 1
           else
-            echo "::set-output name=coverage_passed::false"
+            echo "Test coverage ($COVERAGE%) meets the required threshold."
+          fi
 
       - name: Upload coverage to Codecov
         uses: codecov/codecov-action@v4
